// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDitMTFO2kRfFmA0s6RPHCyCY-xEbDBvNs',
    appId: '1:460051203413:android:eca337d6c099ccf6811bdc',
    messagingSenderId: '460051203413',
    projectId: 'iit-jodhpur-project',
    storageBucket: 'iit-jodhpur-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxfE3ShhNnUPwQGgq8QvCeNb7QXd3uPw',
    appId: '1:460051203413:ios:ef6a63826b0ff43f811bdc',
    messagingSenderId: '460051203413',
    projectId: 'iit-jodhpur-project',
    storageBucket: 'iit-jodhpur-project.appspot.com',
    androidClientId: '460051203413-tgb7pn1tj1dutl1sfe7bhms1unlaohqe.apps.googleusercontent.com',
    iosClientId: '460051203413-fuuc9uvrt19uksapgc58nlm4imo72vuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeProject',
  );

}